name: test

on:
  push:
    paths:
      - "**.go"
      - "go.*"
      - "Makefile"
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Test
        run: make test